webtalk_init -webtalk_dir C:/Users/94201/MUX_DFF_PROJECT/MUX_DFF_PROJECT.sim/sim_1/behav/xsim/xsim.dir/APUF_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Apr 10 14:45:26 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2729669" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f70342d3-be4b-4474-8828-f90f3855f881" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b479e665cc50448b90d11eae4b8aa681" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "80" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2112 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5948_KB" -context "xsim\\usage"
webtalk_transmit -clientid 787383408 -regid "" -xml C:/Users/94201/MUX_DFF_PROJECT/MUX_DFF_PROJECT.sim/sim_1/behav/xsim/xsim.dir/APUF_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/94201/MUX_DFF_PROJECT/MUX_DFF_PROJECT.sim/sim_1/behav/xsim/xsim.dir/APUF_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/94201/MUX_DFF_PROJECT/MUX_DFF_PROJECT.sim/sim_1/behav/xsim/xsim.dir/APUF_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
